name: Deploy Frontend
on:
  push:
    branches:
      - express
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: NPM install
        run: |
          npm install 
      - name: NPM Run Build
        run: |
          npm run build
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' 'node_modules'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: express-frontend
          environment_name: express-frontend-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-735504675342
          region: eu-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
